spring.application.name=auth-service

#JWT secret
jwt.secret=mysupersecuritykey

#Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jesminakhtarneha@gmail.com
spring.mail.password=121Klau$06124
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.enable=true
